version: "3.4"
services:
  elastic:
    # in order to get elastic to work, see https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run-prod-mode
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
    container_name: elasticsearch
    environment:
      - cluster.routing.allocation.disk.threshold_enabled=false
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - xpack.graph.enabled=false
      - xpack.ml.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.security.enabled=false
      - xpack.watcher.enabled=false
      - ELASTIC_PASSWORD=elastic
      - "discovery.type=single-node"
      - TAKE_FILE_OWNERSHIP=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./docker-data/elastic:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.0
    container_name: kibana
    ports:
      - 5601:5601
    depends_on:
      -  elastic

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - ./docker-data/redis:/data

  postgres:
    image: postgres:10
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
